

data AE00;

attrib
USUBJID length = $30.
AESTDTC format = e8601da.
ENSTDTC format = e8601da.
AEREL format = $30.
AEOUT format = $40.
AETERM format = $40.;

SET CRF.CRF_AE_SAMPLE;

*1. DOMAIN 생성;
DOMAIN = 'AE';

*2. 이상반응 없는 경우 제거;
if AEYN = 'N' then delete;

*3. USUBJID 생성;
if length(strip(SUBJID)) = 1 then USUBJID = CATT(STUDYID,'-',SITEID,'-00',SUBJID);
else if length(strip(SUBJID)) = 2 then USUBJID = CATT(STUDYID,'-',SITEID,'-0',SUBJID);
else USUBJID = CATT(STUDYID,'-',SITEID,'-',SUBJID);

*4. AESTDTC 생성;
AESTDTC = AESTDAT;

*5. ENSTDTC 생성;
ENSTDTC = AEENDAT;

*6. AEONGO 생성;
AEONGO = AEENGO;

*7. AESEV 이상값 확인;
if AESEV not in ('MILD' 'MODERATE' 'SEVERE') then put "AESEV Confirmation required " AESEV: ;

*8. AEREL 정제;
if AEREL = 'Y' then AEREL = 'RELATED';
else if AEREL = 'N' then AEREL = 'NOT RELATED';
else if missing(AEREL) then AEREL = 'UNKNOWN';

*9. AEOUT 정제;
if AEOUT = 'RECOVERED/RESOLVED' then AEOUT = 'RECOVERED/RESOLVED';
else if AEOUT = 'ONGOING' then AEOUT = 'NOT RECOVERED/NOT RESOLVED';
else if AEOUT = 'FATAL' then AEOUT = 'FATAL';
else AEOUT = 'UNKNOWN';

*10. AESEQ 생성;
AESEQ = AESPID;

*11. AEDECOD 생성;
if AETERM in ('HEADACHE' 'DIZZINESS' 'COUGH' 'ANOREXIA' 'NAUSEA' 'DEPRESSION' 'DIARRHOEA' 'HYPERTENSION') then AEDECOD = propcase(AETERM);
else if AETERM = 'FEVER' then AEDECOD = 'Pyrexia';
else if AETERM = 'BACK PAIN' then AEDECOD = 'Back pain';
run;

*순서 정리 및 필요 변수 추출;
data SDTM.SDTM_AE_SAMPLE(keep = STUDYID DOMAIN USUBJID AESEQ AETERM AEDECOD AESEV AESER AEACN AEREL AEOUT AESCONG AESDISAB AESDTH AESHOSP AESLIFE AESMIE);
retain STUDYID DOMAIN USUBJID AESEQ AETERM AEDECOD AESEV AESER AEACN AEREL AEOUT AESCONG AESDISAB AESDTH AESHOSP AESLIFE AESMIE;
set ae00;
run;
