
data SDTM.SDTM_TE_SAMPLE(keep = STUDYID DOMAIN ETCD ELEMENT TESTRL TEENRL TEDUR); 
retain STUDYID DOMAIN ETCD ELEMENT TESTRL TEENRL TEDUR;
format ETCD $20. ELEMENT $40. TESTRL $50. TEENRL $50.;
set CRF.CRF_TE_SAMPLE;

*1. 도메인 생성;
DOMAIN = 'TE';

*2. 데이터 정제;
*TESTRL: 시작 규칙;
*TEENRL: 종료 규칙;
if ETCD = 'SCREEN' then do; ETCD = 'SCRN'; TESTRL = 'INFORMED CONSENT'; TEENRL = '2 DAY AFTER START OF ELEMENT'; TEDUR = 'P2D'; output; end;
if ETCD = 'TREAT' then do; ETCD = 'TRT'; ELEMENT = 'TREATMENT PERIOD'; TESTRL = 'FIRST DOSE OF STUDY DRUG'; TEENRL = '2 WEEKS AFTER START OF ELEMENT'; TEDUR = 'P14D'; output; end;
if ETCD = 'FOLLOWUP' then do; TESTRL = 'LAST DOSE OF STUDY DRUG'; TEENRL = '1 MONTH AFTER LAST SCHEDULED VISIT'; TEDUR = 'P30D'; output; end;

run;


*******정리*******;
*ETCD, ELEMENT: 일반적으로 표준화된 코드가 있지만 변동 가능성 있음;
*TESTRL, TEENRL: 프로토콜에 기술된 문장이나 조건을 정리해서 사용(표준화된 코드X);
*TEDUR: e8601 기준;
