

*IG 기준 필수 데이터셋 구축;
data TRIAL.TRIAL_TI_SAMPLE;
retain STUDYID DOMAIN IETESTCD IETEST IECAT TIVERS;
format IETESTCD $4.; 
set 
/*1. TICD: 정렬(include먼저)*/
/*2. TISEQ, TIJUDG, TISTDTC, TIENDTC 제외(필수 변수 아님)*/
/*3. TICD -> IETESTCD, TITERM -> IETEST 변수명 변경*/
PROTOCOL.PROTOCOL_TI_SAMPLE(where = (IETESTCD  = 'INC') DROP = TISEQ TIJUDG TISTDTC TIENDTC rename = (TICD = IETESTCD TITERM = IETEST))
PROTOCOL.PROTOCOL_TI_SAMPLE(where = (IETESTCD ^= 'INC') DROP = TISEQ TIJUDG TISTDTC TIENDTC rename = (TICD = IETESTCD TITERM = IETEST))
;

*4. DOMAIN 생성;
DOMAIN = 'TI';

*5. IETESTCD 값 수정;
**INC -> INCL, EXC -> EXCL;
if IETESTCD = 'INC' then IETESTCD = 'INCL';
if IETESTCD = 'EXC' then IETESTCD = 'EXCL';

*6. IECAT 생성;
**IETESTCD 값에 INCL 해당 -> INCLUSION;
**IETESTCD 값에 EXCL 해당 -> EXCLUSION;
if index(IETESTCD,'INCL') then IECAT = 'INCLUSION';
if index(IETESTCD,'EXCL') then IECAT = 'EXCLUSION';

*7. TIVERS 생성;
**임의의 프로토콜 버전 값(1(문자형)) 입력;
TIVERS = '1';
run;