
/*
STUDYID DOMAIN VISITNUM VISIT VISITDY : 필수
ARMCD TVSTRL TVENRL : 선택
*/

data TRIAL.TRIAL_TV_SAMPLE; 
retain STUDYID DOMAIN VISITNUM VISIT VISITDY ARMCD TVSTRL TVENRL;
format TVSTRL $50. TVENRL $50.;
set PROTOCOL.PROTOCOL_TV_SAMPLE;

*1. 도메인 생성;
DOMAIN = 'TV';

*2. TVSTRL(해당 방문이 언제 시작되는지), TVENRL(해당 방문이 언제 종료되는지) 정제;
if VISIT = 'BASELINE' then do; TVSTRL = 'DAY 1 OF TREATMENT'; TVENRL = 'BASELINE END'; end;
if VISIT = 'WEEK 4' then do; TVSTRL = 'FOLLOW-UP START'; TVENRL = 'END OF WEEK 4'; end;
if VISIT = 'WEEK 8' then do; TVSTRL = 'FOLLOW-UP START'; TVENRL = 'END OF WEEK 8'; end;
if VISIT = 'WEEK 12' then do; TVSTRL = 'FOLLOW-UP START'; TVENRL = 'END OF WEEK 12'; end;
if VISIT = 'WEEK 16' then do; TVSTRL = 'FOLLOW-UP START'; TVENRL = 'END OF WEEK 16'; end;
if VISIT = 'WEEK 20' then do; TVSTRL = 'FOLLOW-UP START'; TVENRL = 'END OF WEEK 20'; end;

run;

